import { TCOParams } from './tco-calculations';

export interface Scenario {
  id: string;
  name: string;
  description: string;
  model1Name: string;
  model1Params: TCOParams;
  model2Name: string;
  model2Params: TCOParams;
  presentationText: string;
}

export const scenarios: Scenario[] = [
  {
    id: 'chatbot-request-volume',
    name: 'Chatbot Request Volume Analysis',
    description: 'Compare GPT-5.4 API vs Llama 3.1 8B cloud-hosted deployment for a chatbot application',
    model1Name: 'GPT-5.4 API',
    model1Params: {
      days: 365,
      modelType: 'api',
      inputTokenPrice: 2.175,
      outputTokenPrice: 13.05,
      contextLength: 4096,
      responseLength: 512,
      requestsPerDay: 25000,
      avgTokensPerRequest: 800,
      avgResponseTokens: 300,
      vectorDb: false,
      embeddingGen: false,
      rerankingModel: false,
      moderationModel: false,
      guardrails: false,
      toolCalls: false,
      embeddingCostPerReq: 0.00001,
      rerankerCostPerReq: 0.0002,
      toolCallsPerRequest: 2,
      caching: false,
      modelRouting: false,
      quantization: false,
      batching: false,
      promptCompression: false,
      fineTuningReduction: false,
      speculativeDecoding: false,
      cacheHitRate: 30,
      routingSmallModelShare: 50,
      routingCostRatio: 0.15,
      tokenReduction: 20,
      fineTuningTokenReduction: 15,
      quantizationThroughputGain: 1.4,
      quantizationQualityRetention: 97,
      specDecodingThroughputGain: 2.0,
      apiBatchDiscount: 50,
      selfHostedBatchUtilizationGain: 40,
      tokensPerSecond: 300,
      gpuPrice: 1.99,
      trainingGpuHours: 0,
      finetuningCost: 0,
      dataPreparationCost: 0,
      hardwareCost: 0,
      engineeringHoursOneTime: 40,
      costPerHour: 150,
      engineeringHoursMonthlyOps: 10,
      cachingImplHours: 16,
      routingImplHours: 28,
      quantizationImplHours: 80,
      batchingImplHours: 24,
      compressionImplHours: 12,
      fineTuningImplHours: 120,
      specDecodingImplHours: 80,
      vectorDbImplHours: 80,
      embeddingGenImplHours: 24,
      rerankingImplHours: 60,
      moderationImplHours: 16,
      guardrailsImplHours: 30,
      toolCallsImplHours: 80,
    },
    model2Name: 'Llama 3.1 8B',
    model2Params: {
      days: 365,
      modelType: 'cloud',
      inputTokenPrice: 0,
      outputTokenPrice: 0,
      contextLength: 4096,
      responseLength: 512,
      requestsPerDay: 25000,
      avgTokensPerRequest: 800,
      avgResponseTokens: 300,
      vectorDb: false,
      embeddingGen: false,
      rerankingModel: false,
      moderationModel: false,
      guardrails: false,
      toolCalls: false,
      embeddingCostPerReq: 0.00001,
      rerankerCostPerReq: 0.0002,
      toolCallsPerRequest: 2,
      caching: false,
      modelRouting: false,
      quantization: false,
      batching: false,
      promptCompression: false,
      fineTuningReduction: false,
      speculativeDecoding: false,
      cacheHitRate: 30,
      routingSmallModelShare: 50,
      routingCostRatio: 0.15,
      tokenReduction: 20,
      fineTuningTokenReduction: 15,
      quantizationThroughputGain: 1.4,
      quantizationQualityRetention: 97,
      specDecodingThroughputGain: 2.0,
      apiBatchDiscount: 50,
      selfHostedBatchUtilizationGain: 40,
      tokensPerSecond: 250,
      gpuPrice: 0.93,
      trainingGpuHours: 0,
      finetuningCost: 0,
      dataPreparationCost: 0,
      hardwareCost: 0,
      engineeringHoursOneTime: 100,
      costPerHour: 150,
      engineeringHoursMonthlyOps: 20,
      cachingImplHours: 16,
      routingImplHours: 28,
      quantizationImplHours: 80,
      batchingImplHours: 24,
      compressionImplHours: 12,
      fineTuningImplHours: 120,
      specDecodingImplHours: 80,
      vectorDbImplHours: 80,
      embeddingGenImplHours: 24,
      rerankingImplHours: 60,
      moderationImplHours: 16,
      guardrailsImplHours: 30,
      toolCallsImplHours: 80,
    },
    presentationText: `Compare **GPT-5.4 API** vs **Llama 3.1 8B cloud-hosted** deployment for a chatbot application. 
    
The scenario illustrates how request volume influences total cost of ownership. API-based deployments generally have lower setup costs, whereas cloud-hosted deployments may become more economical at higher usage levels.

Experiment with request volume, token consumption, and engineering effort to explore when each deployment strategy is most cost-effective.`,
  },
];
